name: Demo Workflow
on: workflow_dispatch
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello World!
      - name: Print few lines
        run: |
          echo First line!
          echo Second line!
        
